Metadata:
  StackName: "s3-scaling-definitions"
AWSTemplateFormatVersion: "2010-09-09"
Description: "Example IAM Role"
Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "s3-scaling-definitions"
      Path: /
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            AWS: "arn:aws:iam::1316120916:role/kube-1-worker"
        Version: '2012-10-17'
      Policies:
      - PolicyName: "AllowS3BucketAccess"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "s3:PutObject"
            - "s3:GetObject"
            - "s3:DeleteObject"
            - "s3:PutObjectAcl"
            Resource:
            - "arn:aws:s3:::schedule-scaling-staging/*"
